name = "cache-homepage"
account_id = "f2497a8b2e32517696337623763577f7"
workers_dev = true
main = "src/index.js"  # Asegúrate de que esta ruta sea correcta
compatibility_date = "2023-10-01"

# Ruta de producción
route = "https://iokone.com/*"

# Entorno de producción (opcional, si necesitas configuraciones específicas)
[env.production]
route = "https://iokone.com/*"
